export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className="m-0 p-0"
        style={{
          background: "linear-gradient(135deg, #000 0%, #ff00cc 100%)",
          minHeight: "100vh",
        }}
      >
        {children}
      </body>
    </html>
  );
}
